### ISSUE TITLE
Theme does not set html theme color meta tag

### ISSUE THREAD

**Issue by evelyndooley** [mxmeinhold/CSHThemeSwitcher#5]
On mobile the theme color in the browser doesn't change to the theme's header color.
![screenshot apr 11 2018 1_18_46 am](https://user-images.githubusercontent.com/31457788/38597553-6d3f2cac-3d26-11e8-8c48-f83b69be2c91.png)

**Comment by mxmeinhold** [comment]
@natedooley What format would the colour codes be needed in? I was going to return `000000`, unless you want it as `#000000`.

**Comment by mxmeinhold** [comment]
@natedooley I've pushed an implementation of this to `dev`, [here](https://themeswitcher-dev.csh.rit.edu). The api route is `/api/colour`. Does this work?
