### ISSUE TITLE
Suggestion: Add API endpoint for retrieving the name of the currently used theme

### ISSUE THREAD

**Issue by mfrancis95** [mxmeinhold/CSHThemeSwitcher#6]
Something like `/api/name` or `/api/get/name`. 

This would open up the possibility of displaying the name of the theme on our web apps and doing specific things based on the theme.

**Comment by mfrancis95** [comment]
Might as well just return the object within the data/themes.json array so we get the CDN too.

**Comment by mfrancis95** [comment]
A better idea might be including a CSS class in each theme that displays the name of the theme, such as:
```
.theme-name::before {
    content: 'Datto';
}
```
or
```
.theme-name::after {
    content: 'Datto';
}
```

**Comment by mxmeinhold** [comment]
Doing so would also reduce the number of requests a service must make to themeswitcher. This is my preferred route.
